# Generated by Django 3.0.4 on 2020-05-19 15:49

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200115_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(default=payments.models._default_batch_description, verbose_name='description'),
        ),
    ]
