# Generated by Django 3.0.3 on 2020-03-25 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_auto_20191106_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contribution',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(7.5)], verbose_name='contribution'),
        ),
    ]  # TODO all existing NULL contribution fields must be set to the amount of the related payment
